### ISSUE TITLE
Error while configuring it

### ISSUE THREAD

**Issue by prateekrastogi** [yahoohung/loopback-graphql-server#1]
Hi,
I was trying to configure graphql server on my existing codebase, but i kept getting the error:
 throw new Error(message);
    ^

Error: userCredentialQueries.userCredentialExists(id:) argument type must be Input Type but got: JSON.
    at invariant (C:\Code\consert\backend\node_modules\loopback-graphql-server\node_modules\graphql\jsutils\invariant.js:19:11)
    at C:\Code\consert\backend\node_modules\loopback-graphql-server\node_modules\graphql\type\definition.js:376:58
    at Array.map (native)
    at C:\Code\consert\backend\node_modules\loopback-graphql-server\node_modules\graphql\type\definition.js:373:44
    at Array.forEach (native)
    at defineFieldMap (C:\Code\consert\backend\node_modules\loopback-graphql-server\node_modules\graphql\type\definition.js:357:14)
    at GraphQLObjectType.getFields (C:\Code\consert\backend\node_modules\loopback-graphql-server\node_modules\graphql\type\definition.js:311:44)
    at typeMapReducer (C:\Code\consert\backend\node_modules\loopback-graphql-server\node_modules\graphql\type\schema.js:209:25)
    at C:\Code\consert\backend\node_modules\loopback-graphql-server\node_modules\graphql\type\schema.js:219:20
    at Array.forEach (native)
    at typeMapReducer (C:\Code\consert\backend\node_modules\loopback-graphql-server\node_modules\graphql\type\schema.js:210:27)
    at Array.reduce (native)
    at new GraphQLSchema (C:\Code\consert\backend\node_modules\loopback-graphql-server\node_modules\graphql\type\schema.js:98:34)
    at getSchema (C:\Code\consert\backend\node_modules\loopback-graphql-server\src\schema\index.js:21:12)
    at module.exports (C:\Code\consert\backend\node_modules\loopback-graphql-server\src\boot.js:20:24)
    at C:\Code\consert\backend\node_modules\loopback-boot\lib\executor.js:445:5

my configuration was default:
 "loopback-graphql-server": {
    "path": "/graphql",
    "graphiqlPath": "/graphiql",
    "subscriptionServer": {
      "disable": true,
      "port": 5000,
      "options": {},
      "socketOptions": {}
    },
    "modelMutationGroups": false,
    "modelQueryGroups": true
  }

Strangely, when trying to do similar config with  loopback graphql relay package written by blueeastcode my graphql server is working fine, it's config is:

 "loopback-graphql-relay": {
    "path": "/graphql",
    "graphiqlPath": "/graphiql",
    "subscriptionServer": {
      "disable": false,
      "port": 5000,
      "options": {},
      "socketOptions": {}
    },
    "viewer": {
      "AccessTokenModel": "accessToken",
      "relation": "user",
      "UserModel": "user"
    }
  }

Any, guesses regarding possible cause of errors? I am guessing it is due to this package being dependent on default models for its configuration.

**Comment by prateekrastogi** [comment]
Also, when i am trying to run your your graphql starter it is working perfectly fine

**Comment by prateekrastogi** [comment]
Hi,
Also, when i am trying to query a remote method of verb get written by extending one of the models in your starter, I am getting the error that callback is not a function. Do you know any workaround for the issue?  The default model methods are working perfectly fine.

**Comment by yahoohung** [comment]
@prateekrastogi Hi, thanks for your information. Here is the example code for adding new remote method 

```
    brand.newCount = function(brandId) {
        return brand.count({
            id: brandId
        })
    }
```

**Comment by yahoohung** [comment]
@prateekrastogi Would you mind sending me your grahqlQL query for me? I tested on the latest version and is look good for me.

```
{
  product{
    productExists(id: "1")
  }
}
```

**Comment by prateekrastogi** [comment]
@yahoohung 
Here is the sample code i am trying to run using remote method and its throwing error that module is not found
  Brand.hello = function() {
    var output ='hello'
    return output
  }

The method is defined as simple get method in corresponding json file

**Comment by prateekrastogi** [comment]
The graphql query for the endpoint is:

query{
  brand{
    brandHello
  }
}

**Comment by yahoohung** [comment]
@prateekrastogi 
Here you are.
```
Brand.hello = function() {
    return new Promise((resolve, reject) => {
        resolve('hello')
    })
}

```

**Comment by prateekrastogi** [comment]
@yahoohung 
Thanks a lot. But, it left with me with more questions than the answer itself. Why are we returning promise instead of simply the value. According to my guess, it's because loopback also supports alternate way to return remote method instead of callback and I was unaware of it whole time. Or, are there any other plausible explanations?

**Comment by prateekrastogi** [comment]
Also, my earlier error regarding usercredentials.id field is present even today. But, when i am using loopback-graphql-relay, its working fine. Basically, those models are used for oauth login using loopback-component-passport and we have to put their location model-config as
"_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models",
      "./node_modules/loopback-component-passport/lib/models"
    ],

Also, it will be quite helpful, if you can inform me changes in this package and bug fixed vs loopback graphql relay by blueeastcode so that i can explore what went wrong, or just use loopback graphql relay in that code.  
Thank you.

**Comment by prateekrastogi** [comment]
Can you also explian me what are these two fields do in component config
"modelMutationGroups": false,
    "modelQueryGroups": true

**Comment by prateekrastogi** [comment]
Hi, 
To reproduce the  'argument type must be Input Type but got: JSON'.  Please clone the [https://github.com/strongloop/loopback-example-passport](url) example and update all the package dependencies using [https://www.npmjs.com/package/npm-check-updates](url). Then, install loopback graphql server module  and modify the component config like you mentioned after installing all the modules of the package.json. Then using npm run start please run the server and you will see the error I am talking about.

**Comment by yahoohung** [comment]
1. All queries and mutations are calling models by using node not the remote method, and a resolve function is a must in graphql. Please check the example here.

```
var {connectionType: ShipConnection} =
  connectionDefinitions({nodeType: shipType});
var factionType = new GraphQLObjectType({
  name: 'Faction',
  fields: () => ({
    ships: {
      type: ShipConnection,
      args: connectionArgs,
      resolve: (faction, args) => connectionFromArray(
        faction.ships.map((id) => data.Ship[id]),
        args
      ),
    }
  }),
});
```
2. Would you mind post your graphql schema so we are explorer more. I think it just some simple mistake.

3. (https://github.com/facebook/relay/issues/551)

**Comment by yahoohung** [comment]
@prateekrastogi I tested the exist function on my current project and is look good. By the way, I recommend you should disable those models from public, see the sample here (https://github.com/strongloop/loopback-example-passport/blob/master/server/model-config.json)

**Comment by yahoohung** [comment]
The reason why I forked the project from blueeastcode is because ...

1. Not supports the functions like gte, lte, and/or etc,
2. Not supports ACL,
3. Not supports where filter in sub-modules
4. Not supports (https://github.com/4Catalyzer/found-relay)
5. Not supports get access token in model by read ctx.options

**Comment by prateekrastogi** [comment]
@yahoohung 
Thanks for clarification. Those changes seems pretty important.  As per as authentication was concerned, I was doing them outside graphql too.  But, I was making models public just for playing around with graphql. And even after just exposing just the user model graphql public with graphql i am getting the same error:
    throw new Error(message);
    ^

Error: userQueries.userExists(id:) argument type must be Input Type but got: JSON.
  
As far as schema is concerned, if i am unable to run the program, I can't think of any other way to generate the schema. But, the steps to reproduce the bug using loopback-example-passport I mentioned earlier are working exactly same. Does your current project also use loopback-component-passport? Also, I am still not clear about these use two fields in the component config:
"modelMutationGroups": false,
"modelQueryGroups": true

**Comment by yahoohung** [comment]
Can you go to (http://localhost:3000/graphiql?query=%7B%0A%20%20user%20%7B%0A%20%20%20%20userExists(id%3A%20%221%22)%0A%20%20%7D%0A%7D) and run it? You will able to see the access denied message. 

```
{
  user {
    userExists(id:"1")
  }
}
```

**Comment by yahoohung** [comment]
For the reason why I created a extra options for grouping query and mutation is because relay looks not support nested mutation schema. I tested on my own project and found some developers reported that can rin in graphql but not working in relay client so I have to provide a extra option for this.

**Comment by prateekrastogi** [comment]
Hi,
But, the error is occuring when i am trying to start the server using i.e. I am unable to run the run the server itself, so I can't access the graphiql in it.   
Okay, I finally understood those two options i was little confused by terminology.

**Comment by prateekrastogi** [comment]
And , if I am using your starter without using loopback-component-passport and try to run the query you just mentioned it's working as expected and I am receiving userExists: true response. But, with loopback-component-passport, I am not able to start the server itself, even after trying to delete some models.

**Comment by prateekrastogi** [comment]
@yahoohung 
Hi, As I was trying to debug your code to run my server, I found a little deviation in your code from blueeastcode especially regarding the generation of query items by calling getquery method imported from default index file in schema/query folder and used while generating model query in schema/index file. Also, your code for generating the queries fields in that file is slightly different from blueastcode. But, as per as my understanding they are generating same fields object with only extra field in blueeast code i.e. " viewer" field. Digging further, I found that viewer field is generally used for accessing information about user in user login context. 
Can you tell me the reasoning for removing viewer field ? Are you also changing the query fields generated assuming default parameters are passed ? Is it the possible that error while running the server through your config is due to exclusion of viewer field?

**Comment by prateekrastogi** [comment]
@yahoohung 
I manged to run your project with my code. Weirdly, just declaring the loopback-graphql-relay in dependecy together with loopback-graphql-server in package.json was the cause of error. Although, I never concurrently configured to use them together in any particular setup. As, I managed to run it I found the message of websocket subscription server running not displayed. But, when I tried to do the same with loopback-graphql-server version 1.1.0, I saw notification of websocket server running. I digged the code of your module little bit and saw the code regarding subscriptions missing in present version 1.1.7 but that code was present in 1.1.0. If so, did you removed the support of subscriptions or is it silently running? What are the problems that forced the removal of subscription support in your present build?

**Comment by yahoohung** [comment]
I tested the module with (https://github.com/strongloop/loopback-example-passport) and I cannot find any problem. Can you share your repository to me?

**Comment by yahoohung** [comment]
The reason why I removed subscriptions server is because the original code in blueeastcode was not compatible with the latest graphql, react, etc.

**Comment by prateekrastogi** [comment]
@yahoohung 
I manged to run your code with loopback-example-passport, there was some weird issues arising due to inclusion of blueeastcode in the package dependency.
Are there any future plans to support subscriptions compatible with the latest versions of graphql etc.?
Thanks.

**Comment by efaby** [comment]
@yahoohung 
I have the similar error 

**Error: MyUserQueries.MyUserFindById(id:) argument type must be Input Type but got: JSON.**

This error show when I am trying to start the server.

Thanks for your help.
